package main;
import "core:strings"
import "core:strconv"
import "core:fmt"
import llvm "./llvm-bind"


/*
This module will, with the help of the llvm binding, generate the llvm irl
from the parsed ast generated by the parser.
It works be going trough each function and creating the declerations and statments
inside the function bodies
*/



LLVM_Generator :: struct {
    context_ref: llvm.ContextRef,
    builder_ref: llvm.BuilderRef,
    module_ref: llvm.ModuleRef,

    current_function: llvm.ValueRef,

    // holds variables
    refs : map[string]llvm.ValueRef,
    structs : map[string]llvm.TypeRef
}

get_tmp_name :: proc () -> cstring {
    return "tmp"
}


get_llvm_type :: proc(g: ^LLVM_Generator ,type: Type) -> llvm.TypeRef {
    #partial switch v in type {
        case Basic:
        #partial switch v {
            case .INT:    return llvm.Int32TypeInContext(g.context_ref)
            case .BOOL:   return llvm.Int1TypeInContext(g.context_ref)
            case .VOID:   return llvm.VoidTypeInContext(g.context_ref)
            case .FLOAT:  return llvm.FloatTypeInContext(g.context_ref)
            case .DOUBLE: return llvm.DoubleTypeInContext(g.context_ref)
            case .STRING: return llvm.PointerTypeInContext(g.context_ref, 0)
        }
        case Pointer: return llvm.PointerTypeInContext(g.context_ref, 0)
        case Array: panic("TODO")
        case Struct_Decl:
        return g.structs[v.name]

    }
    fmt.println(type)
    panic("TODO")
}

create_function_decl :: proc (g: ^LLVM_Generator, func: Function_Decl) -> llvm.ValueRef {
    type := get_llvm_type(g, func.type)
    arg_length := len(func.args)
    param_types := make([]llvm.TypeRef, arg_length)
    for i in 0..<arg_length  {
        arg := func.args[i]
        param_types[i] = get_llvm_type(g, arg.type)
    }

    func_type := llvm.FunctionType(type, raw_data(param_types), u32(arg_length), 0)
    
    fun :=  llvm.AddFunction(g.module_ref, fmt.ctprintf(func.name), func_type)

    return fun
}

create_decl :: proc (g: ^LLVM_Generator, decl_u: Decl) -> llvm.ValueRef {
    switch decl in decl_u {
    case Variable_Decl:
        type := get_llvm_type(g,decl.type)

        var := llvm.BuildAlloca(g.builder_ref, type, get_tmp_name())

        g.refs[decl.name] = var

        if decl.initlizer != nil {

            val := create_expression(g, decl.initlizer)
            return llvm.BuildStore(
                g.builder_ref,
                val,
                var,
            )
        }
        return var
        
    case Function_Decl: panic("TODO")
    case Struct_Decl: panic("TODO")
    }
    panic("HERE")
}

create_function :: proc (g: ^LLVM_Generator, func: Function_Decl) -> llvm.ValueRef {
    func_ref := create_function_decl(g, func);
    g.current_function = func_ref
    bb_name := cstring("entry\x00")
    entry_bb := llvm.AppendBasicBlockInContext(g.context_ref, func_ref, bb_name)
    llvm.PositionBuilderAtEnd(g.builder_ref, entry_bb)
    if func.block == nil do panic("TODO")

    // create stack variables from arguments
    // This is so we get pass by value
    // we create new stack variables and copy over the argument data
    for i in 0..<len(func.args) {
        arg := func.args[i]
        param := llvm.GetParam(func_ref, u32(i))
        type := get_llvm_type(g, arg.type)
        var := llvm.BuildAlloca(g.builder_ref, type, "arg_var")

        llvm.BuildStore(g.builder_ref,
                        param,
                        var)
        
        g.refs[arg.name] = var
    }

    created_return := false
    for item in func.block.items {
        switch v in item{
        case Decl:
            create_decl(g, v);
        case Stmt:
            if _, ok := v.(Return_Stmt); ok {
                created_return = true
            }
            create_stmt(g, v);
        }
    }
    if !created_return {
        llvm.BuildRetVoid(g.builder_ref)
    }
    
    return func_ref
}

create_call :: proc(g: ^LLVM_Generator, expr: Expr_Call) -> llvm.ValueRef {
    fn_ref := llvm.GetNamedFunction(g.module_ref, fmt.ctprintf(expr.name))

    if fn_ref == nil {
        parser_panic(Expr(expr), fmt.tprintf("Could not find %s", expr.name))
    }
    fn_type := llvm.GlobalGetValueType(fn_ref)

    a_len := len(expr.args)
    llvm_args := make([]llvm.ValueRef, a_len)
    defer delete(llvm_args)
    
    for i in 0..<a_len {
        arg := expr.args[i]
        llvm_args[i] = create_expression(g, arg^)
    }
    // if return type is void we should pass empty string otherwise
    // we want to capture the return
    str := check_type(get_expr_type(expr), Basic(.VOID)) ? cstring("") : cstring("ans")

    call := llvm.BuildCall2(
        g.builder_ref,
        fn_type,
        fn_ref,
        raw_data(llvm_args),
        u32(a_len),
        str
    )

    return call
}

create_add :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)

    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT)) || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFAdd(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFAdd(g.builder_ref, left, right, get_tmp_name())
    else                                                                     do return llvm.BuildAdd(g.builder_ref, left, right, get_tmp_name())
}


create_sub :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)


    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT))  || check_type(rt, Basic(.FLOAT))  do return llvm.BuildFSub(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFSub(g.builder_ref, left, right, get_tmp_name())
    else                                                 do return llvm.BuildSub(g.builder_ref, left, right, get_tmp_name())
}


create_mult :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)


    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT)) || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFMul(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFMul(g.builder_ref, left, right, get_tmp_name())
    else                                                 do return llvm.BuildMul(g.builder_ref, left, right, get_tmp_name())
}

create_div :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)


    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT)) || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFDiv(g.builder_ref, left, right, get_tmp_name())
    else if  check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFDiv(g.builder_ref, left, right, get_tmp_name())
    else                                                 do return llvm.BuildSDiv(g.builder_ref, left, right, get_tmp_name())
}

create_assign :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {

    left_val : llvm.ValueRef = {}

    #partial switch v in left {
        case Expr_MemberAccess:
        left_val = create_member_access(g, v)

        case Expr_Identifier:
        ref := g.refs[v.value]
        left_val = ref
        
        case Expr_Unary:
        if v.operator != .UP do panic("TODO")
        t, ok := get_expr_type(v.operand^).(Pointer)
        if !ok do panic("TODO")

        ptr := create_expression(g, v.operand^);
        type := get_llvm_type(g, get_expr_type(v.operand^))
        left_val = ptr
        
        case Expr_Subscript:
        type := get_llvm_type(g, get_expr_type(v.left^))
        ptr := create_expression(g, v.left^);        
        index := create_expression(g, v.index^)

        ptrel := llvm.BuildGEP2(
            g.builder_ref,
            type,
            ptr,
            &index,
            1,
            cstring("element_ptr"),
        )

        left_val = ptrel
    }
    right_val := create_expression(g, right)

    
    return llvm.BuildStore(
        g.builder_ref,
        right_val,
        left_val
    )
    // fmt.println(left)
    // panic("TODO")
}

create_cond :: proc (g: ^LLVM_Generator, left, right: Expr, op: llvm.IntPredicate) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)

    cond := llvm.BuildICmp(
        g.builder_ref,
        op,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_and_cond :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)
    cond := llvm.BuildAnd(
        g.builder_ref,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_or_cond :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)
    cond := llvm.BuildOr(
        g.builder_ref,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_binary :: proc (g: ^LLVM_Generator, expr: Expr_Binary) -> llvm.ValueRef {

    #partial switch expr.op {
        case .PLUS:    return create_add(g, expr.left^, expr.right^)
        case .MINUS:   return create_sub(g, expr.left^, expr.right^)
        case .STAR:    return create_mult(g, expr.left^, expr.right^)
        case .DIVIDE:  return create_div(g, expr.left^, expr.right^)
        
        case .EQUAL:   return create_assign(g, expr.left^, expr.right^)
        
        case .LESS:    return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SLT)
        case .GREATER: return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SGT)
        case .LEQ:     return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SLE)
        case .GEQ:     return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SGE)
        case .EQ:      return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.EQ)
        case .AND:     return create_and_cond(g, expr.left^, expr.right^)
        case .OR:      return create_or_cond(g, expr.left^, expr.right^)

    }
    panic("TODO")
}

create_number :: proc(g: ^LLVM_Generator, expr: Expr_Number) -> llvm.ValueRef {
    #partial switch t in expr.type {
    case Basic:
        #partial switch t {
            case .INT:
            val,ok := strconv.parse_int(expr.value)
            if !ok do parser_panic(expr, "Not an integer")
            return llvm.ConstInt(get_llvm_type(g,Basic(.INT)), u64(val), 0)
            case .FLOAT:
            value,_ := strings.replace(expr.value, "f", "",1)
            val,ok := strconv.parse_f32(value)
            if !ok do parser_panic(expr, "Not an float")
            return llvm.ConstReal(get_llvm_type(g,Basic(.FLOAT)), f64(val))
            case .DOUBLE:
            value,_ := strings.replace(expr.value, "d", "",1)
            val,ok := strconv.parse_f64(value)
            if !ok do parser_panic(expr, "Not an double")
            return llvm.ConstReal(get_llvm_type(g,Basic(.DOUBLE)), f64(val))
            case .BOOL:
            val : u64 = expr.value == "true" ? 1 : 0
            return llvm.ConstInt(get_llvm_type(g, Basic(.BOOL)), val, 0)

        }
    }
    panic("WRONG TYPE")
}

load_pointer :: proc (g: ^LLVM_Generator, ptr: llvm.ValueRef, type: llvm.TypeRef) -> llvm.ValueRef {
    return llvm.BuildLoad2(
        g.builder_ref,
        type,
        ptr,
        "deref_ptr"
    )
}


create_member_access :: proc(g: ^LLVM_Generator, expr: Expr_MemberAccess) -> llvm.ValueRef {
    object, found_var := g.refs[expr.obj.name]
    if !found_var do panic("asd")

    strc,ok := expr.obj.type.(Struct_Decl)
    if !ok do panic("asd")

    indices := make([]llvm.ValueRef, 2)
    indices[0] = llvm.ConstInt(llvm.Int32TypeInContext(g.context_ref),0,0)
    for i in 0..<len(strc.members) {
        member := strc.members[i]
        if member.name == expr.member {
            indices[1] = llvm.ConstInt(get_llvm_type(g, member.type), u64(i), 0)
        }
    }

    type_name, ok2 := g.structs[strc.name]
    if !ok2 do panic("asd")

    val := llvm.BuildGEP2(
        g.builder_ref,
        type_name,
        object,
        &indices[0],
        u32(len(indices)),
        "member_ptr",
    )
    return val
}



create_expression :: proc(g: ^LLVM_Generator, expr: Expr) -> llvm.ValueRef{
    switch v in expr{
    case Expr_MemberAccess:
        ptr := create_member_access(g, v)
        return load_pointer(g, ptr, get_llvm_type(g, get_expr_type(v)))
    case Expr_Array: panic("TODO")
    case Expr_Subscript:
        type := get_llvm_type(g, get_expr_type(v.left^))
        ptr := create_expression(g, v.left^);        
        index := create_expression(g, v.index^)

        ptrel := llvm.BuildGEP2(
            g.builder_ref,
            type,
            ptr,
                &index,
            1,
            cstring("element_ptr"),
        )

        return llvm.BuildLoad2(
            g.builder_ref,
            type,
            ptrel,
            "ptrval"
        )

    case Expr_Number:
        return create_number(g, v);
    case Expr_String:
        s,_ := strings.replace_all(v.value, "\\n", "\n")
        s,_ = strings.replace_all(s, "\\n", "\n")
        s,_ = strings.replace_all(s, "\\t", "\t")
        s,_ = strings.replace_all(s, "\\r", "\r")
        s,_ = strings.replace_all(s, "\\\\", "\\")
        s,_ = strings.replace_all(s, "\\\"", "\"")
        value := strings.clone_to_cstring(strings.trim(s, "\""))

        return llvm.BuildGlobalStringPtr(
            g.builder_ref,
            value,
            fmt.ctprintf("str")
        )
    case Expr_Identifier:
        // type is not set
        ref,ok := g.refs[v.value]
        if !ok do panic("TODO Could not find the variable")
        type := get_llvm_type(g, v.type)
        
        return llvm.BuildLoad2(g.builder_ref, type, ref, get_tmp_name())
        //panic("TODO")
    case Expr_Binary: return create_binary(g, v)
    case Expr_Call:
        return create_call(g, v);
    case Expr_Unary:
        #partial switch v.operator {
            case .UP:
            
            type := get_llvm_type(g, get_expr_type(v.operand^))
            ptr := create_expression(g, v.operand^);
            return load_pointer(g, ptr, type)
            case .AMPER:
            lvalue, ok := v.operand.(Expr_Identifier);
            if !ok do parser_panic(lvalue, "asd")

            return g.refs[lvalue.value]
        }
        panic("TODO")
    }
    panic("TODO")
}

create_stmt :: proc(g: ^LLVM_Generator, stmt: Stmt) -> llvm.ValueRef {
    switch v in stmt{
    case Expr:
        return create_expression(g, v)
    case Return_Stmt:
        if v.value == nil do panic("TODO VALUE NULL")
        val := create_expression(g, v.value^)
        return llvm.BuildRet(g.builder_ref, val)

    case If_Stmt:
        cond_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.cond",
        )
        body_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.body",
        )
        else_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.else",
        )
       end_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.end",
        )

        llvm.BuildBr(g.builder_ref, cond_bb)
        llvm.PositionBuilderAtEnd(g.builder_ref, cond_bb)
        cond := create_expression(g, v.condition^)

        llvm.BuildCondBr(
            g.builder_ref,
            cond,
            body_bb,
            else_bb,
        )
        // body
        llvm.PositionBuilderAtEnd(g.builder_ref, body_bb)
        create_stmt(g, v.block^)
        // jump to end
        llvm.BuildBr(g.builder_ref, end_bb)

        // else
        llvm.PositionBuilderAtEnd(g.builder_ref, else_bb)
        if v.else_block != nil do create_stmt(g, v.else_block^)
        // jump to end
        llvm.BuildBr(g.builder_ref, end_bb)


        // end
        llvm.PositionBuilderAtEnd(g.builder_ref, end_bb)

        return nil
    case While_Stmt:
        cond_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.cond",
        )

        body_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.body",
        )

        end_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.end",
        )

        // Jump into the condition.
        llvm.BuildBr(g.builder_ref, cond_bb)
        // while.cond:
        llvm.PositionBuilderAtEnd(g.builder_ref, cond_bb)

        cond := create_expression(g, v.condition^)


        llvm.BuildCondBr(
            g.builder_ref,
            cond,
            body_bb,
            end_bb,
        )

        // while.body:
        llvm.PositionBuilderAtEnd(g.builder_ref, body_bb)

        create_stmt(g, v.block^)

        // Unless the body already terminated (return/break/etc.),
        // loop back to the condition.
        llvm.BuildBr(g.builder_ref, cond_bb)

        // while.end:
        llvm.PositionBuilderAtEnd(g.builder_ref, end_bb)

        return nil
    case Block:
        for item in v.items {
            switch v in item{
            case Decl:
                create_decl(g, v);
            case Stmt:
                if _, ok := v.(Return_Stmt); ok {
                    //created_return = true
                }
                create_stmt(g, v);
            }
        }
        return nil
    }
    panic("TODO")
}

gen_program :: proc (g: ^LLVM_Generator, p: Program, i_file, o_file: string) {
    context_ref := llvm.ContextCreate()
    defer llvm.ContextDispose(context_ref)

    g.context_ref = context_ref

    mod_name := strings.clone_to_cstring(i_file)
    module_ref := llvm.ModuleCreateWithNameInContext(mod_name, context_ref)
    defer llvm.DisposeModule(module_ref)
    g.module_ref = module_ref

    builder_ref := llvm.CreateBuilderInContext(context_ref)
    defer llvm.DisposeBuilder(builder_ref)
    g.builder_ref = builder_ref
    
    for struc in p.structs {
        struct_type := llvm.StructCreateNamed(g.context_ref, strings.clone_to_cstring(struc.name))

        field_types := make([dynamic]llvm.TypeRef)

        for field in struc.members {
            append(&field_types, get_llvm_type(g, field.type))
        }

        llvm.StructSetBody(
            struct_type,
            raw_data(field_types),
            u32(len(field_types)),
            0,
        )
        g.structs[struc.name] = struct_type
    }

    for func in p.functions {
        if func.extern do create_function_decl(g, func)
        else do create_function(g, func)
    }
    // write the irl to a file
    error_msg: cstring
    if llvm.PrintModuleToFile(module_ref, fmt.ctprintf(o_file), &error_msg) != 0 {
        fmt.eprintln("Failed to write module:", error_msg)
        llvm.DisposeMessage(error_msg)
    }
}
