package main;
import "core:strings"
import "core:strconv"
import "core:fmt"
import "core:mem"
import llvm "../llvm-bind"


/*
This module will, with the help of the llvm binding, generate the llvm irl
from the parsed ast generated by the parser.
It works be going trough each function and creating the declerations and statments
inside the function bodies
*/



LLVM_Generator :: struct {
    context_ref: llvm.ContextRef,
    builder_ref: llvm.BuilderRef,
    module_ref: llvm.ModuleRef,

    current_function: llvm.ValueRef,

    // holds variables
    refs : map[string]llvm.ValueRef,
    structs : map[string]llvm.TypeRef
}

get_tmp_name :: proc () -> cstring {
    return "tmp"
}


get_llvm_type :: proc(g: ^LLVM_Generator ,type: Type) -> (llvm.TypeRef, bool) #optional_ok {
    #partial switch v in type {
        case Basic:
        #partial switch v {
            case .INT:    return llvm.Int32TypeInContext(g.context_ref), true
            case .BYTE:    return llvm.Int8TypeInContext(g.context_ref), true
            case .BOOL:   return llvm.Int1TypeInContext(g.context_ref), true
            case .VOID:   return llvm.VoidTypeInContext(g.context_ref), true
            case .FLOAT:  return llvm.FloatTypeInContext(g.context_ref), true
            case .DOUBLE: return llvm.DoubleTypeInContext(g.context_ref), true
            case .STRING: return llvm.PointerTypeInContext(g.context_ref, 0), true
        }
        case Pointer: return llvm.PointerTypeInContext(g.context_ref, 0), true
        case Array:
        if v.of == nil do panic("ARRAY TYPE IS NIL")
        
        of, found := get_llvm_type(g, v.of^)
        if !found do return {}, false;
        return llvm.ArrayType2(of, v.length), true

        case NamedType:
        panic("SHOULDNT BE THIS RIGHT")
        case StructType:
        
        type, exists := g.structs[v.path[len(v.path)-1]]
        if !exists {
            logln("Couln't find struct in this file create it", v.path[:])
            type = create_struct(g, Struct_Decl{
                name = v.path[len(v.path)-1],
                members = v.members
            })
        }
        return type, true
    }
    fmt.println(type)
    panic("TODO")
}

create_function_decl :: proc (g: ^LLVM_Generator, func: Function_Decl, package_name: string) -> llvm.ValueRef {
    type,_ := get_llvm_type(g, func.type)
    arg_length := len(func.args)
    param_types := make([]llvm.TypeRef, arg_length)
    for i in 0..<arg_length  {
        arg := func.args[i]
        param_types[i],_ = get_llvm_type(g, arg.type)
    }

    func_type := llvm.FunctionType(type, raw_data(param_types), u32(arg_length), 0)
    if package_name != "" {
        name := fmt.ctprintf("{}_{}", package_name, func.name)
        logln("CREATE", name)
        fun :=  llvm.AddFunction(g.module_ref, name, func_type)
        g.refs[func.name] = fun
        return fun
    } else {
        name := fmt.ctprintf("{}", func.name)
        logln("CREATE", name)
        fun :=  llvm.AddFunction(g.module_ref, name, func_type)
        g.refs[func.name] = fun
        return fun

    }

}

create_decl :: proc (g: ^LLVM_Generator, decl_u: Decl) -> llvm.ValueRef {
    logln("create declerations")
    switch decl in decl_u {
    case Variable_Decl:
        logln("Creating variable", decl_to_string(decl))
        type,ok := get_llvm_type(g,decl.type)
        if !ok {
            fmt.println(type)
            panic("AHH")
        }
        logln("==done with type", decl_to_string(decl))

        var := llvm.BuildAlloca(g.builder_ref, type, get_tmp_name())

        g.refs[decl.name] = var

        if decl.initlizer != nil {
            logln("init", expr_to_string(decl.initlizer^), ":", get_expr_type(decl.initlizer^))
            val := create_expression(g, decl.initlizer^)
            return llvm.BuildStore(
                g.builder_ref,
                val,
                var,
            )
        }
        logln("done with variable", decl_to_string(decl))
        return var
        
    case Function_Decl: panic("TODO")
    case Struct_Decl:   panic("TODO")
    case Package_Decl:  panic("ASD")
    }
    panic("HERE")
}

create_function :: proc (g: ^LLVM_Generator, func: Function_Decl, package_name: string) -> llvm.ValueRef {
    // if we are main we dont change 
    func_ref := create_function_decl(g, func, func.name != "main" ? package_name : "");
    g.current_function = func_ref
    bb_name := cstring("entry\x00")
    entry_bb := llvm.AppendBasicBlockInContext(g.context_ref, func_ref, bb_name)
    llvm.PositionBuilderAtEnd(g.builder_ref, entry_bb)
    if func.block == nil do panic("TODO")

    // create stack variables from arguments
    // This is so we get pass by value
    // we create new stack variables and copy over the argument data
    for i in 0..<len(func.args) {
        arg := func.args[i]
        param := llvm.GetParam(func_ref, u32(i))
        type,_ := get_llvm_type(g, arg.type)
        var := llvm.BuildAlloca(g.builder_ref, type, "arg_var")

        llvm.BuildStore(g.builder_ref,
                        param,
                        var)
        
        g.refs[arg.name] = var
    }

    created_return := false
    for item in func.block.items {
        switch v in item{
        case Decl:
            create_decl(g, v);
        case Stmt:
            if _, ok := v.(Return_Stmt); ok {
                created_return = true
            }
            create_stmt(g, v);
        }
    }
    if !created_return {
        llvm.BuildRetVoid(g.builder_ref)
    }
    
    return func_ref
}

get_package_name :: proc(name_: string) -> string {
    ename := name_
    name, ok := strings.replace_all(ename, ".","_")
    return name
}

create_call :: proc(g: ^LLVM_Generator, expr: Expr_Call) -> llvm.ValueRef {
    if expr.name == nil do panic("AJ AJ AJ")
    name := get_package_name(expr_to_string(expr.name^))
    logln("create call", name)
    //fn_ref := llvm.GetNamedFunction(g.module_ref, fmt.ctprintf(name))
    fn_ref, exists := g.refs[name]
    if !exists {
        fn_ref = create_function_decl(g, Function_Decl{
            name = name,
            type = expr.type,
            args = nil,
            
        },"")
        //panic("HAVE TO CREATE THE FUNCTION")
    }

    if fn_ref == nil {
        parser_panic(Expr(expr), fmt.tprintf("Could not find {}", expr_to_string(expr.name^)))
    }
    fn_type := llvm.GlobalGetValueType(fn_ref)

    a_len := len(expr.args)
    llvm_args := make([]llvm.ValueRef, a_len)
    defer delete(llvm_args)
    
    for i in 0..<a_len {
        arg := expr.args[i]
        llvm_args[i] = create_expression(g, arg^)
    }
    // if return type is void we should pass empty string otherwise
    // we want to capture the return
    str := check_type(get_expr_type(expr), Basic(.VOID)) ? cstring("") : cstring("ans")

    call := llvm.BuildCall2(
        g.builder_ref,
        fn_type,
        fn_ref,
        raw_data(llvm_args),
        u32(a_len),
        str
    )

    return call
}

create_add :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)

    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT)) || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFAdd(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFAdd(g.builder_ref, left, right, get_tmp_name())
    else                                                                     do return llvm.BuildAdd(g.builder_ref, left, right, get_tmp_name())
}


create_sub :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)


    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT))  || check_type(rt, Basic(.FLOAT))  do return llvm.BuildFSub(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFSub(g.builder_ref, left, right, get_tmp_name())
    else                                                 do return llvm.BuildSub(g.builder_ref, left, right, get_tmp_name())
}


create_mult :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)


    left := create_expression(g, left)
    right := create_expression(g, right)

    if      check_type(lt, Basic(.FLOAT)) || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFMul(g.builder_ref, left, right, get_tmp_name())
    else if check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE)) do return llvm.BuildFMul(g.builder_ref, left, right, get_tmp_name())
    else                                                 do return llvm.BuildMul(g.builder_ref, left, right, get_tmp_name())
}

create_div :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    lt := get_expr_type(left)
    rt := get_expr_type(right)

    left := create_expression(g, left)
    right := create_expression(g, right)

    if       check_type(lt, Basic(.FLOAT))  || check_type(rt, Basic(.FLOAT))   do return llvm.BuildFDiv(g.builder_ref, left, right, get_tmp_name())
    else if  check_type(lt, Basic(.DOUBLE)) || check_type(rt, Basic(.DOUBLE))  do return llvm.BuildFDiv(g.builder_ref, left, right, get_tmp_name())
    else                                                                       do return llvm.BuildSDiv(g.builder_ref, left, right, get_tmp_name())
}

create_subscript_ptr :: proc(g: ^LLVM_Generator, ptr_expr: Expr_Subscript, element_type: Type) -> llvm.ValueRef {
            
    
    type,_:= get_llvm_type     (g, element_type)
    ptr   := create_expression (g, ptr_expr.left^);
    index := create_expression (g, ptr_expr.index^)

    ptrel := llvm.BuildGEP2(
        g.builder_ref,
        type,
        ptr,
            &index,
        1,
        cstring("element_ptr"),
    )
    return ptrel;
}

create_subscript_arr :: proc(g: ^LLVM_Generator, expr: Expr_Subscript, element_type: Type) -> llvm.ValueRef {
    left_type := get_expr_type(expr.left^)
    
    ptr   := create_expression(g, expr.left^, true)
    index := create_expression (g, expr.index^)

    array_llvm_type,_ := get_llvm_type(g, left_type)
    zero := llvm.ConstInt(
        llvm.Int32TypeInContext(g.context_ref),
        0,
        0,
    )
    indices := [2]llvm.ValueRef{
        zero,
        index,
    }
    return llvm.BuildGEP2(
        g.builder_ref,
        array_llvm_type,
        ptr,
            &indices[0],
        2,
        cstring("element_ptr"),
    )
}


create_assign :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {
    logln("create assignment")
    left_val : llvm.ValueRef = {}

    #partial switch v in left {
        case Expr_MemberAccess:
        left_val = create_member_access(g, v)

        case Expr_Identifier:
        ref := g.refs[v.value]
        left_val = ref
        
        case Expr_Unary:
        if v.operator != .UP do panic("TODO")
        t, ok := get_expr_type(v.operand^).(Pointer)
        if !ok do panic("TODO")

        ptr := create_expression(g, v.operand^);
        type,_ := get_llvm_type(g, get_expr_type(v.operand^))
        left_val = ptr
        
        case Expr_Subscript:
        logln("left is exprsubscript", v.left)

        if p,ok := get_expr_type(v.left^).(Pointer); ok {
            if p.to == nil do panic("HERE")
            left_val = create_subscript_ptr(g, v, p.to^)
        }

        // FIXME add check if its over array length
        if arr,ok := get_expr_type(v.left^).(Array); ok {
            if arr.of == nil do panic("HERE")
            left_val = create_subscript_arr(g, v, arr.of^)
        }


    }
    right_val := create_expression(g, right)

    
    return llvm.BuildStore(
        g.builder_ref,
        right_val,
        left_val
    )
    // fmt.println(left)
    // panic("TODO")
}

create_cond :: proc (g: ^LLVM_Generator, left, right: Expr, op: llvm.IntPredicate) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)

    cond := llvm.BuildICmp(
        g.builder_ref,
        op,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_and_cond :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)
    cond := llvm.BuildAnd(
        g.builder_ref,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_or_cond :: proc (g: ^LLVM_Generator, left, right: Expr) -> llvm.ValueRef {

    lhs := create_expression(g,left)
    rhs := create_expression(g,right)
    cond := llvm.BuildOr(
        g.builder_ref,
        lhs,
        rhs,
        "cond",
    )
    return cond
}

create_binary :: proc (g: ^LLVM_Generator, expr: Expr_Binary) -> llvm.ValueRef {

    #partial switch expr.op {
        case .PLUS:    return create_add(g, expr.left^, expr.right^)
        case .MINUS:   return create_sub(g, expr.left^, expr.right^)
        case .STAR:    return create_mult(g, expr.left^, expr.right^)
        case .DIVIDE:  return create_div(g, expr.left^, expr.right^)
        
        case .EQUAL:   return create_assign(g, expr.left^, expr.right^)
        
        case .LESS:    return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SLT)
        case .GREATER: return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SGT)
        case .LEQ:     return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SLE)
        case .GEQ:     return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.SGE)
        case .EQ:      return create_cond(g, expr.left^, expr.right^, llvm.IntPredicate.EQ)
        case .AND:     return create_and_cond(g, expr.left^, expr.right^)
        case .OR:      return create_or_cond(g, expr.left^, expr.right^)

    }
    panic("TODO")
}

create_number :: proc(g: ^LLVM_Generator, expr: Expr_Number) -> llvm.ValueRef {
    #partial switch t in expr.type {
    case Basic:
        #partial switch t {
            case .BYTE:
            val,ok := strconv.parse_int(expr.value)
            if !ok do parser_panic(expr, "Not an integer")
            return llvm.ConstInt(get_llvm_type(g,Basic(.BYTE)), u64(val), 0)

            case .INT:
            val,ok := strconv.parse_int(expr.value)
            if !ok do parser_panic(expr, "Not an integer")
            return llvm.ConstInt(get_llvm_type(g,Basic(.INT)), u64(val), 0)
            
            case .FLOAT:
            value,_ := strings.replace(expr.value, "f", "",1)
            val,ok := strconv.parse_f32(value)
            if !ok do parser_panic(expr, "Not an float")
            return llvm.ConstReal(get_llvm_type(g,Basic(.FLOAT)), f64(val))
            
            case .DOUBLE:
            value,_ := strings.replace(expr.value, "d", "",1)
            value,_ = strings.replace(expr.value, "f", "",1) // float can be double
            val,ok := strconv.parse_f64(value)
            
            if !ok do parser_panic(expr, "Not an double")
            return llvm.ConstReal(get_llvm_type(g,Basic(.DOUBLE)), f64(val))
            
            case .BOOL:
            val : u64 = expr.value == "true" ? 1 : 0
            return llvm.ConstInt(get_llvm_type(g, Basic(.BOOL)), val, 0)

        }
    }
    panic("WRONG TYPE")
}

load_pointer :: proc (g: ^LLVM_Generator, ptr: llvm.ValueRef, type: llvm.TypeRef) -> llvm.ValueRef {
    return llvm.BuildLoad2(
        g.builder_ref,
        type,
        ptr,
        "deref_ptr"
    )
}

get_var :: proc(g: ^LLVM_Generator, expr: Expr) -> (llvm.ValueRef, bool) {
    logln("looking for var ref", expr_to_string(expr))
    if par,is := expr.(Expr_MemberAccess); is {
        return get_var(g, par.obj^)
    }
    if id,is := expr.(Expr_Identifier); is {
        logln("found var", id.value)
        return g.refs[id.value], true
    }
    return {}, false
}

// alfred.data.age
get_member_index :: proc(type: Type, member: string) -> (int, bool) {
    struc_t, is := type.(StructType)
    if !is do return -1, false
    
    for i in 0..<len(struc_t.members) {
        m := struc_t.members[i]
        logln(member, "==", m.name)
        if m.name == member do return i, true
    }

    return 0, false
}


create_member_access :: proc(g: ^LLVM_Generator, expr: Expr_MemberAccess) -> llvm.ValueRef {
    logln("Creating member access")
    logln(expr_to_string(expr))

    obj_ptr := create_expression(g, expr.obj^, gen_address=true)
    obj_type := get_expr_type(expr.obj^)
    obj_type = checker_dereferance(obj_type)
    
    logln("obj type is ", obj_type)


    member_index, found := get_member_index(obj_type, expr.member);
    if !found do parser_panic(expr, "Could not find member for object")

    llvm_type, found2 := get_llvm_type(g, obj_type)
    if !found2 do panic("AHH")

    member := llvm.BuildStructGEP2(
        g.builder_ref,
        llvm_type,
        obj_ptr,
        u32(member_index),
        "member",
    )
    logln("done with", expr_to_string(expr))

    return member;
}


create_expression :: proc(g: ^LLVM_Generator, expr: Expr, gen_address: bool = false) -> llvm.ValueRef{
    switch v in expr{
    case Expr_MemberAccess:
        logln("generating memberaccess")
        ptr := create_member_access(g, v)
        if gen_address do return ptr
        t,_ := get_llvm_type(g, get_expr_type(v))
        return load_pointer(g, ptr, t)
    case Expr_Array: panic("TODO")
    case Expr_Subscript:
        logln("generating subscript")
        type,_a := get_llvm_type(g, get_expr_type(v))
        ptrel: llvm.ValueRef
        if p, is := get_expr_type(v.left^).(Pointer); is {
            ptrel = create_subscript_ptr(g,v, p.to^);
        }
        if p, is := get_expr_type(v.left^).(Array); is {
            ptrel = create_subscript_arr(g,v, p.of^);
        }

        if gen_address do return ptrel

        return llvm.BuildLoad2(
            g.builder_ref,
            type,
            ptrel,
            "ptrval"
        )
    case Expr_Number:
        logln("generating num")
        return create_number(g, v);
    case Expr_String:
        logln("generating string")
        s,_ := strings.replace_all(v.value, "\\n", "\n")
        s,_ = strings.replace_all(s, "\\n", "\n")
        s,_ = strings.replace_all(s, "\\t", "\t")
        s,_ = strings.replace_all(s, "\\r", "\r")
        s,_ = strings.replace_all(s, "\\\\", "\\")
        s,_ = strings.replace_all(s, "\\\"", "\"")
        value := strings.clone_to_cstring(strings.trim(s, "\""))

        return llvm.BuildGlobalStringPtr(
            g.builder_ref,
            value,
            fmt.ctprintf("str")
        )
    case Expr_Identifier:
        logln("generating identifer")
        // type is not set
        ref,ok := g.refs[v.value]
        if !ok do panic("TODO Could not find the variable")
        
        if gen_address do return ref

        type,_ := get_llvm_type(g, v.type)
        return llvm.BuildLoad2(g.builder_ref, type, ref, get_tmp_name())
    case Expr_Binary: return create_binary(g, v)
    case Expr_Call:
        return create_call(g, v);
    case Expr_Unary:
        logln("generating unary")
        #partial switch v.operator {
            case .UP:
            
            type,_ := get_llvm_type(g, get_expr_type(v.operand^))
            ptr := create_expression(g, v.operand^, gen_address);
             
            if gen_address do return ptr;
            
            return load_pointer(g, ptr, type)

            case .AMPER:
            var,found := get_var(g, v.operand^)
            if !found do panic("asd")
            
            return var
            
        }
        panic("TODO")
    }
    panic("TODO")
}

create_stmt :: proc(g: ^LLVM_Generator, stmt: Stmt) -> llvm.ValueRef {
    switch v in stmt{
    case Expr:
        return create_expression(g, v)
    case Return_Stmt:
        if v.value == nil do panic("TODO VALUE NULL")
        val := create_expression(g, v.value^)
        return llvm.BuildRet(g.builder_ref, val)

    case If_Stmt:
        cond_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.cond",
        )
        body_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.body",
        )
        else_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.else",
        )
       end_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "if.end",
        )

        llvm.BuildBr(g.builder_ref, cond_bb)
        llvm.PositionBuilderAtEnd(g.builder_ref, cond_bb)
        cond := create_expression(g, v.condition^)

        llvm.BuildCondBr(
            g.builder_ref,
            cond,
            body_bb,
            else_bb,
        )
        // body
        llvm.PositionBuilderAtEnd(g.builder_ref, body_bb)
        create_stmt(g, v.block^)
        // jump to end
        llvm.BuildBr(g.builder_ref, end_bb)

        // else
        llvm.PositionBuilderAtEnd(g.builder_ref, else_bb)
        if v.else_block != nil do create_stmt(g, v.else_block^)
        // jump to end
        llvm.BuildBr(g.builder_ref, end_bb)


        // end
        llvm.PositionBuilderAtEnd(g.builder_ref, end_bb)

        return nil
    case While_Stmt:
        cond_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.cond",
        )

        body_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.body",
        )

        end_bb := llvm.AppendBasicBlockInContext(
            g.context_ref,
            g.current_function,
            "while.end",
        )

        // Jump into the condition.
        llvm.BuildBr(g.builder_ref, cond_bb)
        // while.cond:
        llvm.PositionBuilderAtEnd(g.builder_ref, cond_bb)

        cond := create_expression(g, v.condition^)


        llvm.BuildCondBr(
            g.builder_ref,
            cond,
            body_bb,
            end_bb,
        )

        // while.body:
        llvm.PositionBuilderAtEnd(g.builder_ref, body_bb)

        create_stmt(g, v.block^)

        // Unless the body already terminated (return/break/etc.),
        // loop back to the condition.
        llvm.BuildBr(g.builder_ref, cond_bb)

        // while.end:
        llvm.PositionBuilderAtEnd(g.builder_ref, end_bb)

        return nil
    case Block:
        for item in v.items {
            switch v in item{
            case Decl:
                create_decl(g, v);
            case Stmt:
                if _, ok := v.(Return_Stmt); ok {
                    //created_return = true
                }
                create_stmt(g, v);
            }
        }
        return nil
    }
    panic("TODO")
}

create_struct :: proc(g: ^LLVM_Generator, struc: Struct_Decl) -> llvm.TypeRef {
    logln("creasting struct", struc.name)
    struct_type := llvm.StructCreateNamed(g.context_ref, strings.clone_to_cstring(struc.name))

    field_types := make([dynamic]llvm.TypeRef)

    logln("membners", struc.members)

    for field in struc.members {
        dptr := checker_dereferance(field.type)
        fmt.println(decl_to_string(field^))
        if nt, is := dptr.(StructType); is {
            llvm_type:= get_llvm_type(g, dptr)
            append(&field_types, llvm_type)
        }
        else {
            append(&field_types, get_llvm_type(g, field.type))
        }
    }

    llvm.StructSetBody(
        struct_type,
        raw_data(field_types),
        u32(len(field_types)),
        0,
    )
    g.structs[struc.name] = struct_type
    return struct_type
}

gen_program :: proc (g: ^LLVM_Generator, p: Package, t: ^SymbolTable, i_file, o_file: string) {

    context_ref := llvm.ContextCreate()
    defer llvm.ContextDispose(context_ref)

    g.context_ref = context_ref

    mod_name := strings.clone_to_cstring(i_file)
    module_ref := llvm.ModuleCreateWithNameInContext(mod_name, context_ref)
    defer llvm.DisposeModule(module_ref)
    g.module_ref = module_ref

    builder_ref := llvm.CreateBuilderInContext(context_ref)
    defer llvm.DisposeBuilder(builder_ref)
    g.builder_ref = builder_ref

    for import_ in p.imports {
        logln("handeling import", expr_to_string(import_.value^))
        if symbol, found := symbol_table_lookup(t, import_.value); found {
            fmt.println("found", expr_to_string(import_.value^))
            #partial switch v in symbol.node {
                case Function_Decl:
                name := strings.split(expr_to_string(import_.value^),".")[0]
                create_function_decl(g, v, name)
                case Variable_Decl: panic("TODO")
                case Struct_Decl:  create_struct(g, v)
            }
        }

    }

    for struc in p.structs {
        create_struct(g, struc^)
    }

    for func in p.functions {
        if func.extern do create_function_decl(g, func^, "")
        else do create_function(g, func^, p.package_name)
    }
    // write the irl to a file
    error_msg: cstring
    if llvm.PrintModuleToFile(module_ref, fmt.ctprintf(o_file), &error_msg) != 0 {
        fmt.eprintln("Failed to write module:", error_msg)
        llvm.DisposeMessage(error_msg)
    }
}
